import { Alert, AlertDescription, AlertTitle } from "@camox/ui/alert";
import { PanelContent, PanelHeader } from "@camox/ui/panel";

import { PagePicker } from "./PagePicker";
import { PageTree } from "./PageTree";
import { PublicationRow } from "./PublicationRow";

export type PreviewedPage = {
  id: number;
  metaTitle: string | null;
  pathSegment: string;
  fullPath: string;
  livePublishedCheckpointId: number | null;
  status: "draft" | "published" | "modified";
  modifiedReason:
    | { reason: "self" }
    | { reason: "layout"; layoutId: number; layoutHandle: string; affectedPagesCount: number }
    | { reason: "both"; layoutId: number; layoutHandle: string; affectedPagesCount: number }
    | null;
};

export const PageNavigatorHeader = ({ page }: { page?: PreviewedPage }) => (
  <PanelHeader className="flex flex-col gap-2 p-2">
    <div className="flex w-full">
      <PagePicker />
    </div>
    {page && <PublicationRow target={{ kind: "page", page }} />}
  </PanelHeader>
);

const PageNavigatorSidebar = ({ page }: { page?: PreviewedPage }) => {
  return (
    <>
      <PageNavigatorHeader page={page} />
      <PanelContent className="flex grow basis-0 flex-col gap-2 overflow-auto p-2">
        {page ? (
          <PageTree />
        ) : (
          <Alert>
            <AlertTitle>No page blocks</AlertTitle>
            <AlertDescription>
              This page’s content is generated by its layout, rather than assembled from page
              blocks.
            </AlertDescription>
          </Alert>
        )}
      </PanelContent>
    </>
  );
};

export { PageNavigatorSidebar };
