/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CamoxRouteImport } from './routes/_camox'
import { Route as CamoxCmxStudioRouteImport } from './routes/_camox/cmx-studio'
import { Route as CamoxCmxRouteImport } from './routes/_camox/cmx'
import { Route as CamoxSplatRouteImport } from './routes/_camox/$'
import { Route as CamoxCmxStudioBlocksRouteImport } from './routes/_camox/cmx-studio.blocks'
import { Route as CamoxCmxStudioSplatRouteImport } from './routes/_camox/cmx-studio.$'

const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CamoxRoute = CamoxRouteImport.update({
  id: '/_camox',
  getParentRoute: () => rootRouteImport,
} as any)
const CamoxCmxStudioRoute = CamoxCmxStudioRouteImport.update({
  id: '/cmx-studio',
  path: '/cmx-studio',
  getParentRoute: () => CamoxRoute,
} as any)
const CamoxCmxRoute = CamoxCmxRouteImport.update({
  id: '/cmx',
  path: '/cmx',
  getParentRoute: () => CamoxRoute,
} as any)
const CamoxSplatRoute = CamoxSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CamoxRoute,
} as any)
const CamoxCmxStudioBlocksRoute = CamoxCmxStudioBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => CamoxCmxStudioRoute,
} as any)
const CamoxCmxStudioSplatRoute = CamoxCmxStudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CamoxCmxStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/custom': typeof CustomRoute
  '/$': typeof CamoxSplatRoute
  '/cmx': typeof CamoxCmxRoute
  '/cmx-studio': typeof CamoxCmxStudioRouteWithChildren
  '/cmx-studio/$': typeof CamoxCmxStudioSplatRoute
  '/cmx-studio/blocks': typeof CamoxCmxStudioBlocksRoute
}
export interface FileRoutesByTo {
  '/custom': typeof CustomRoute
  '/$': typeof CamoxSplatRoute
  '/cmx': typeof CamoxCmxRoute
  '/cmx-studio': typeof CamoxCmxStudioRouteWithChildren
  '/cmx-studio/$': typeof CamoxCmxStudioSplatRoute
  '/cmx-studio/blocks': typeof CamoxCmxStudioBlocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_camox': typeof CamoxRouteWithChildren
  '/custom': typeof CustomRoute
  '/_camox/$': typeof CamoxSplatRoute
  '/_camox/cmx': typeof CamoxCmxRoute
  '/_camox/cmx-studio': typeof CamoxCmxStudioRouteWithChildren
  '/_camox/cmx-studio/$': typeof CamoxCmxStudioSplatRoute
  '/_camox/cmx-studio/blocks': typeof CamoxCmxStudioBlocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/custom'
    | '/$'
    | '/cmx'
    | '/cmx-studio'
    | '/cmx-studio/$'
    | '/cmx-studio/blocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/custom'
    | '/$'
    | '/cmx'
    | '/cmx-studio'
    | '/cmx-studio/$'
    | '/cmx-studio/blocks'
  id:
    | '__root__'
    | '/_camox'
    | '/custom'
    | '/_camox/$'
    | '/_camox/cmx'
    | '/_camox/cmx-studio'
    | '/_camox/cmx-studio/$'
    | '/_camox/cmx-studio/blocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CamoxRoute: typeof CamoxRouteWithChildren
  CustomRoute: typeof CustomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_camox': {
      id: '/_camox'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CamoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_camox/cmx-studio': {
      id: '/_camox/cmx-studio'
      path: '/cmx-studio'
      fullPath: '/cmx-studio'
      preLoaderRoute: typeof CamoxCmxStudioRouteImport
      parentRoute: typeof CamoxRoute
    }
    '/_camox/cmx': {
      id: '/_camox/cmx'
      path: '/cmx'
      fullPath: '/cmx'
      preLoaderRoute: typeof CamoxCmxRouteImport
      parentRoute: typeof CamoxRoute
    }
    '/_camox/$': {
      id: '/_camox/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof CamoxSplatRouteImport
      parentRoute: typeof CamoxRoute
    }
    '/_camox/cmx-studio/blocks': {
      id: '/_camox/cmx-studio/blocks'
      path: '/blocks'
      fullPath: '/cmx-studio/blocks'
      preLoaderRoute: typeof CamoxCmxStudioBlocksRouteImport
      parentRoute: typeof CamoxCmxStudioRoute
    }
    '/_camox/cmx-studio/$': {
      id: '/_camox/cmx-studio/$'
      path: '/$'
      fullPath: '/cmx-studio/$'
      preLoaderRoute: typeof CamoxCmxStudioSplatRouteImport
      parentRoute: typeof CamoxCmxStudioRoute
    }
  }
}

interface CamoxCmxStudioRouteChildren {
  CamoxCmxStudioSplatRoute: typeof CamoxCmxStudioSplatRoute
  CamoxCmxStudioBlocksRoute: typeof CamoxCmxStudioBlocksRoute
}

const CamoxCmxStudioRouteChildren: CamoxCmxStudioRouteChildren = {
  CamoxCmxStudioSplatRoute: CamoxCmxStudioSplatRoute,
  CamoxCmxStudioBlocksRoute: CamoxCmxStudioBlocksRoute,
}

const CamoxCmxStudioRouteWithChildren = CamoxCmxStudioRoute._addFileChildren(
  CamoxCmxStudioRouteChildren,
)

interface CamoxRouteChildren {
  CamoxSplatRoute: typeof CamoxSplatRoute
  CamoxCmxRoute: typeof CamoxCmxRoute
  CamoxCmxStudioRoute: typeof CamoxCmxStudioRouteWithChildren
}

const CamoxRouteChildren: CamoxRouteChildren = {
  CamoxSplatRoute: CamoxSplatRoute,
  CamoxCmxRoute: CamoxCmxRoute,
  CamoxCmxStudioRoute: CamoxCmxStudioRouteWithChildren,
}

const CamoxRouteWithChildren = CamoxRoute._addFileChildren(CamoxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CamoxRoute: CamoxRouteWithChildren,
  CustomRoute: CustomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
