/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CamoxRouteImport } from './routes/_camox'
import { Route as CamoxStudioRouteImport } from './routes/_camox/studio'
import { Route as CamoxSplatRouteImport } from './routes/_camox/$'
import { Route as CamoxStudioPlaygroundRouteImport } from './routes/_camox/studio.playground'
import { Route as CamoxStudioAssetsRouteImport } from './routes/_camox/studio.assets'
import { Route as CamoxStudioSplatRouteImport } from './routes/_camox/studio.$'

const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CamoxRoute = CamoxRouteImport.update({
  id: '/_camox',
  getParentRoute: () => rootRouteImport,
} as any)
const CamoxStudioRoute = CamoxStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CamoxRoute,
} as any)
const CamoxSplatRoute = CamoxSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CamoxRoute,
} as any)
const CamoxStudioPlaygroundRoute = CamoxStudioPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => CamoxStudioRoute,
} as any)
const CamoxStudioAssetsRoute = CamoxStudioAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => CamoxStudioRoute,
} as any)
const CamoxStudioSplatRoute = CamoxStudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CamoxStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/custom': typeof CustomRoute
  '/$': typeof CamoxSplatRoute
  '/studio': typeof CamoxStudioRouteWithChildren
  '/studio/$': typeof CamoxStudioSplatRoute
  '/studio/assets': typeof CamoxStudioAssetsRoute
  '/studio/playground': typeof CamoxStudioPlaygroundRoute
}
export interface FileRoutesByTo {
  '/custom': typeof CustomRoute
  '/$': typeof CamoxSplatRoute
  '/studio': typeof CamoxStudioRouteWithChildren
  '/studio/$': typeof CamoxStudioSplatRoute
  '/studio/assets': typeof CamoxStudioAssetsRoute
  '/studio/playground': typeof CamoxStudioPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_camox': typeof CamoxRouteWithChildren
  '/custom': typeof CustomRoute
  '/_camox/$': typeof CamoxSplatRoute
  '/_camox/studio': typeof CamoxStudioRouteWithChildren
  '/_camox/studio/$': typeof CamoxStudioSplatRoute
  '/_camox/studio/assets': typeof CamoxStudioAssetsRoute
  '/_camox/studio/playground': typeof CamoxStudioPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/custom'
    | '/$'
    | '/studio'
    | '/studio/$'
    | '/studio/assets'
    | '/studio/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/custom'
    | '/$'
    | '/studio'
    | '/studio/$'
    | '/studio/assets'
    | '/studio/playground'
  id:
    | '__root__'
    | '/_camox'
    | '/custom'
    | '/_camox/$'
    | '/_camox/studio'
    | '/_camox/studio/$'
    | '/_camox/studio/assets'
    | '/_camox/studio/playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CamoxRoute: typeof CamoxRouteWithChildren
  CustomRoute: typeof CustomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_camox': {
      id: '/_camox'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CamoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_camox/studio': {
      id: '/_camox/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof CamoxStudioRouteImport
      parentRoute: typeof CamoxRoute
    }
    '/_camox/$': {
      id: '/_camox/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof CamoxSplatRouteImport
      parentRoute: typeof CamoxRoute
    }
    '/_camox/studio/playground': {
      id: '/_camox/studio/playground'
      path: '/playground'
      fullPath: '/studio/playground'
      preLoaderRoute: typeof CamoxStudioPlaygroundRouteImport
      parentRoute: typeof CamoxStudioRoute
    }
    '/_camox/studio/assets': {
      id: '/_camox/studio/assets'
      path: '/assets'
      fullPath: '/studio/assets'
      preLoaderRoute: typeof CamoxStudioAssetsRouteImport
      parentRoute: typeof CamoxStudioRoute
    }
    '/_camox/studio/$': {
      id: '/_camox/studio/$'
      path: '/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof CamoxStudioSplatRouteImport
      parentRoute: typeof CamoxStudioRoute
    }
  }
}

interface CamoxStudioRouteChildren {
  CamoxStudioSplatRoute: typeof CamoxStudioSplatRoute
  CamoxStudioAssetsRoute: typeof CamoxStudioAssetsRoute
  CamoxStudioPlaygroundRoute: typeof CamoxStudioPlaygroundRoute
}

const CamoxStudioRouteChildren: CamoxStudioRouteChildren = {
  CamoxStudioSplatRoute: CamoxStudioSplatRoute,
  CamoxStudioAssetsRoute: CamoxStudioAssetsRoute,
  CamoxStudioPlaygroundRoute: CamoxStudioPlaygroundRoute,
}

const CamoxStudioRouteWithChildren = CamoxStudioRoute._addFileChildren(
  CamoxStudioRouteChildren,
)

interface CamoxRouteChildren {
  CamoxSplatRoute: typeof CamoxSplatRoute
  CamoxStudioRoute: typeof CamoxStudioRouteWithChildren
}

const CamoxRouteChildren: CamoxRouteChildren = {
  CamoxSplatRoute: CamoxSplatRoute,
  CamoxStudioRoute: CamoxStudioRouteWithChildren,
}

const CamoxRouteWithChildren = CamoxRoute._addFileChildren(CamoxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CamoxRoute: CamoxRouteWithChildren,
  CustomRoute: CustomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
