import { readFileSync, writeFileSync } from "node:fs";
import { resolve, relative } from "node:path";
import type { ViteDevServer } from "vite";
import { writeIfChanged } from "./utils";

const HEADER = `/* ============================================================================
 * AUTO-GENERATED BY CAMOX — DO NOT EDIT
 *
 * This file is managed by the Camox Vite plugin and should stay gitignored.
 * Any manual edits will be automatically reverted by the dev server.
 * ============================================================================ */

`;

function generateCamoxApp(): string {
  return (
    HEADER +
    `import { createApp } from 'camox/createApp';
import type { Block } from 'camox/createBlock';
import type { Layout } from 'camox/createLayout';

// Auto-import all blocks from the blocks directory
const blockModules = import.meta.glob<{ block: Block }>('./blocks/*.{ts,tsx}', {
  eager: true,
});
const blocks = Object.values(blockModules).map((mod) => mod.block);

// Auto-import all layouts from the layouts directory
const layoutModules = import.meta.glob<{ layout: Layout }>(
  './layouts/*.{ts,tsx}',
  { eager: true },
);
const layouts = Object.values(layoutModules).map((mod) => mod.layout);

export const camoxApp = createApp({
  blocks,
  layouts,
});
`
  );
}

function getAppFileEntries(appRoot: string) {
  return [
    { path: resolve(appRoot, "src/camox/app.ts"), content: generateCamoxApp() },
  ];
}

export function generateAppFile(appRoot: string) {
  for (const entry of getAppFileEntries(appRoot)) {
    writeIfChanged(entry.path, entry.content);
  }
}

export function watchAppFile(server: ViteDevServer, appRoot: string) {
  const entries = getAppFileEntries(appRoot);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox app file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });

  server.watcher.on("unlink", (deletedPath) => {
    const expected = expectedByPath.get(deletedPath);
    if (!expected) return;

    const rel = relative(server.config.root, deletedPath);
    server.config.logger.warn(
      `Camox app file "${rel}" was deleted — recreating.`,
      { timestamp: true },
    );
    writeFileSync(deletedPath, expected, "utf-8");
  });
}
