import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { iconCollectionIds, loadIconCollection } from "@camox/api-contract";

export async function generateIconTypes(root: string, prefix?: string) {
  const ids = prefix ? iconCollectionIds(await loadIconCollection(prefix)) : [];
  mkdirSync(resolve(root, "src/camox"), { recursive: true });
  const union = ids.map((id) => JSON.stringify(id));
  const type = union.length > 1 ? `\n      | ${union.join("\n      | ")}` : (union[0] ?? "never");
  writeFileSync(
    resolve(root, "src/camox/icons.gen.d.ts"),
    `// Generated by Camox. Do not edit.\nexport {};\ndeclare global {\n  interface CamoxIconRegistry {\n    ids:${union.length > 1 ? "" : " "}${type};\n  }\n}\n`,
  );
  return ids;
}
