import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve, basename } from "node:path";

import { writeIfChanged } from "./utils";

/** Keep file identities stable across moves without executing application modules. */
export function generateLayoutFiles(appRoot: string) {
  const directory = resolve(appRoot, "src/layouts");
  if (!existsSync(directory)) return;
  const declarations: string[] = [];
  for (const file of readdirSync(directory).sort()) {
    if (!/\.(ts|tsx)$/.test(file) || file.endsWith(".d.ts")) continue;
    const id = basename(file).replace(/\.(ts|tsx)$/, "");
    const path = resolve(directory, file);
    let source = readFileSync(path, "utf8");
    if (!source.trim()) {
      source = `import { createLayout } from "camox/createLayout";

export const Layout = createLayout(${JSON.stringify(id)})({
  kind: "curated",
  title: ${JSON.stringify(id)},
  description: "",
  blocks: { before: [], after: [] },
  buildMetaTitle: ({ pageMetaTitle }) => pageMetaTitle,
  component: ({ children }) => <main><Layout.BeforeBlocks />{children}<Layout.AfterBlocks /></main>,
});
`;
    }
    source = source.replace(
      /(createLayout\(\s*)["'][^"']+["'](\s*\)\s*\()/g,
      `$1${JSON.stringify(id)}$2`,
    );
    writeIfChanged(path, source);
    const segments = id.split(".");
    const route =
      "/" +
      segments
        .map((segment) => (segment.startsWith("$") ? `:${segment.slice(1)}` : segment))
        .join("/");
    const params = segments
      .filter((segment) => segment.startsWith("$"))
      .map((segment) => `${JSON.stringify(segment.slice(1))}: string`)
      .join("; ");
    declarations.push(
      `${JSON.stringify(id)}: { route: ${JSON.stringify(route)}; params: { ${params} } };`,
    );
  }
  writeIfChanged(
    resolve(appRoot, "src/camox/layouts.gen.d.ts"),
    `// Generated by Camox.\nimport "camox/createLayout";\ndeclare module "camox/createLayout" {\n  interface LayoutFileRoutes {\n    ${declarations.join("\n    ")}\n  }\n}\n`,
  );
}
