import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, relative } from "node:path";
import type { ViteDevServer } from "vite";
import { writeIfChanged } from "./utils";

const HEADER = `/* ============================================================================
 * AUTO-GENERATED BY CAMOX — DO NOT EDIT
 *
 * This file is managed by the Camox Vite plugin and should stay gitignored.
 * Any manual edits will be automatically reverted by the dev server.
 * ============================================================================ */

`;

function generateCamoxLayout(convexUrl: string): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxProvider } from "camox/CamoxProvider";
import { camoxApp } from "@/camox";

export const Route = createFileRoute("/_camox")({
  component: CamoxPathlessLayout,
});

function CamoxPathlessLayout() {
  return (
    <CamoxProvider camoxApp={camoxApp} convexUrl="${convexUrl}">
      <Outlet />
    </CamoxProvider>
  );
}
`
  );
}

function generatePageRoute(convexUrl: string): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import {
  createMarkdownMiddleware,
  createPageLoader,
  createPageHead,
  PageRouteComponent,
} from "camox/_internal/pageRoute";
import { camoxApp } from "@/camox";

const markdownMiddleware = createMarkdownMiddleware("${convexUrl}");
const loader = createPageLoader();
const head = createPageHead(camoxApp);

export const Route = createFileRoute("/_camox/$")({
  server: {
    middleware: [markdownMiddleware],
  },
  component: App,
  loader,
  head,
});

function App() {
  const { page } = Route.useLoaderData();
  return <PageRouteComponent page={page} />;
}
`
  );
}

function generateOgRoute(): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { createOgHandler } from "camox/_internal/ogRoute";
import { camoxApp } from "@/camox";

export const Route = createFileRoute("/_camox/og")({
  server: {
    handlers: createOgHandler(camoxApp),
  },
});
`
  );
}

function generateCmxRedirect(): string {
  return (
    HEADER +
    `import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/_camox/cmx")({
  component: RouteComponent,
  loader: () => {
    throw redirect({ to: "/cmx-studio" });
  },
});

function RouteComponent() {
  return null;
}
`
  );
}

function generateCmxStudio(): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxStudio } from "camox/CamoxStudio";

export const Route = createFileRoute("/_camox/cmx-studio")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxStudio>
      <Outlet />
    </CamoxStudio>
  );
}
`
  );
}

function generateCmxStudioCatchAll(): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxStudio } from "camox/CamoxStudio";

export const Route = createFileRoute("/_camox/cmx-studio/$")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxStudio>
      <Outlet />
    </CamoxStudio>
  );
}
`
  );
}

function generateCmxStudioContent(): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { CamoxContent } from "camox/CamoxContent";

export const Route = createFileRoute("/_camox/cmx-studio/content")({
  component: RouteComponent,
});

function RouteComponent() {
  return <CamoxContent />;
}
`
  );
}

function getRouteFileEntries(routesDir: string, convexUrl: string) {
  const camoxDir = resolve(routesDir, "_camox");
  return [
    { path: resolve(routesDir, "_camox.tsx"), content: generateCamoxLayout(convexUrl) },
    { path: resolve(camoxDir, "$.tsx"), content: generatePageRoute(convexUrl) },
    { path: resolve(camoxDir, "og.tsx"), content: generateOgRoute() },
    { path: resolve(camoxDir, "cmx.tsx"), content: generateCmxRedirect() },
    { path: resolve(camoxDir, "cmx-studio.tsx"), content: generateCmxStudio() },
    { path: resolve(camoxDir, "cmx-studio.$.tsx"), content: generateCmxStudioCatchAll() },
    { path: resolve(camoxDir, "cmx-studio.content.tsx"), content: generateCmxStudioContent() },
  ];
}

export function generateRouteFiles(routesDir: string, convexUrl: string) {
  const camoxDir = resolve(routesDir, "_camox");
  mkdirSync(camoxDir, { recursive: true });

  for (const entry of getRouteFileEntries(routesDir, convexUrl)) {
    writeIfChanged(entry.path, entry.content);
  }
}

export function watchRouteFiles(
  server: ViteDevServer,
  routesDir: string,
  convexUrl: string,
) {
  const entries = getRouteFileEntries(routesDir, convexUrl);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox route file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });
}
