import { mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve, relative } from "node:path";

import type { ViteDevServer } from "vite-plus";

import { STUDIO_ROUTE_SEGMENT } from "../studio/routes";
import { writeIfChanged } from "./utils";

const HEADER = `/* ============================================================================
 * AUTO-GENERATED BY CAMOX — DO NOT EDIT
 *
 * This file is managed by the Camox Vite plugin and should stay gitignored.
 * Any manual edits will be automatically reverted by the dev server.
 * ============================================================================ */

/* eslint-disable */

// @ts-nocheck

`;

function generatePageRoute(authenticationUrl: string): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import {
  createMarkdownMiddleware,
  createPageLoader,
  createPageHead,
  PageRouteComponent,
} from "camox/_internal/pageRoute";
import { CamoxProvider } from "camox/CamoxProvider";
import { camoxApp } from "@/camox/app";

const markdownMiddleware = createMarkdownMiddleware(__CAMOX_API_URL__, __CAMOX_PROJECT_SLUG__, __CAMOX_ENVIRONMENT_NAME__);
const loader = createPageLoader(__CAMOX_API_URL__, __CAMOX_PROJECT_SLUG__, __CAMOX_ENVIRONMENT_NAME__);
const head = createPageHead(camoxApp);

export const Route = createFileRoute("/(camox)/(_preview)/$")({
  server: {
    middleware: [markdownMiddleware],
  },
  component: RouteComponent,
  notFoundComponent: () => <div>No Camox page on this path</div>,
  loader,
  head,
});

function RouteComponent() {
  return (
    <CamoxProvider camoxApp={camoxApp} authenticationUrl="${authenticationUrl}" apiUrl={__CAMOX_API_URL__} projectSlug={__CAMOX_PROJECT_SLUG__} environmentName={__CAMOX_ENVIRONMENT_NAME__}>
      <PageRouteComponent />
    </CamoxProvider>
  );
}
`
  );
}

function generateOgRoute(): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { createOgHandler } from "camox/_internal/ogRoute";
import { camoxApp } from "@/camox/app";

export const Route = createFileRoute("/(camox)/(_preview)/og")({
  server: {
    handlers: createOgHandler(camoxApp),
  },
});
`
  );
}

function generateCamoxStudio(authenticationUrl: string): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxProvider } from "camox/CamoxProvider";
import { CamoxStudio } from "camox/CamoxStudio";
import { camoxApp } from "@/camox/app";

export const Route = createFileRoute("/(camox)/(_studio)/${STUDIO_ROUTE_SEGMENT}")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxProvider camoxApp={camoxApp} authenticationUrl="${authenticationUrl}" apiUrl={__CAMOX_API_URL__} projectSlug={__CAMOX_PROJECT_SLUG__} environmentName={__CAMOX_ENVIRONMENT_NAME__}>
      <CamoxStudio>
        <Outlet />
      </CamoxStudio>
    </CamoxProvider>
  );
}
`
  );
}

function generateCamoxStudioCatchAll(): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxStudio } from "camox/CamoxStudio";

export const Route = createFileRoute("/(camox)/(_studio)/${STUDIO_ROUTE_SEGMENT}/$")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxStudio>
      <Outlet />
    </CamoxStudio>
  );
}
`
  );
}

function generateCamoxStudioContent(suffix = ""): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { CamoxContent } from "camox/CamoxContent";

export const Route = createFileRoute("/(camox)/(_studio)/${STUDIO_ROUTE_SEGMENT}/content${suffix}")({
  component: RouteComponent,
});

function RouteComponent() {
  return <CamoxContent />;
}
`
  );
}

type RouteFilesOptions = {
  routesDir: string;
  authenticationUrl: string;
};

function getRouteFileEntries({ routesDir, authenticationUrl }: RouteFilesOptions) {
  const groupDir = resolve(routesDir, "(camox)");
  const previewDir = resolve(groupDir, "(_preview)");
  const studioDir = resolve(groupDir, "(_studio)");
  return [
    {
      path: resolve(previewDir, "$.tsx"),
      content: generatePageRoute(authenticationUrl),
    },
    { path: resolve(previewDir, "og.tsx"), content: generateOgRoute() },
    {
      path: resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.tsx`),
      content: generateCamoxStudio(authenticationUrl),
    },
    {
      path: resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.$.tsx`),
      content: generateCamoxStudioCatchAll(),
    },
    {
      path: resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.content.tsx`),
      content: generateCamoxStudioContent(),
    },
    {
      path: resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.content.assets.tsx`),
      content: generateCamoxStudioContent("/assets"),
    },
  ];
}

function removeObsoleteRouteFiles(routesDir: string) {
  const camoxDir = resolve(routesDir, "_camox");
  const studioDir = resolve(routesDir, "(camox)", "(_studio)");
  const obsoletePaths = [
    resolve(routesDir, "_camox.tsx"),
    resolve(camoxDir, "cmx.tsx"),
    resolve(camoxDir, "$.tsx"),
    resolve(camoxDir, "og.tsx"),
    resolve(camoxDir, "cmx-studio.tsx"),
    resolve(camoxDir, "cmx-studio.$.tsx"),
    resolve(camoxDir, "cmx-studio.content.tsx"),
    resolve(studioDir, "cmx.tsx"),
    resolve(studioDir, "cmx-studio.tsx"),
    resolve(studioDir, "cmx-studio.$.tsx"),
    resolve(studioDir, "cmx-studio.content.tsx"),
    resolve(routesDir, "(camox)", "(_preview)", "$.tsx"),
    resolve(routesDir, "(camox)", "(_preview)", "og.tsx"),
    resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.tsx`),
    resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.$.tsx`),
    resolve(studioDir, `${STUDIO_ROUTE_SEGMENT}.content.tsx`),
  ];

  for (const filePath of obsoletePaths) {
    try {
      const current = readFileSync(filePath, "utf-8");
      if (!current.startsWith(HEADER)) continue;
      unlinkSync(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
  }
}

export function cleanupGeneratedRouteFiles(routesDir: string) {
  removeObsoleteRouteFiles(routesDir);
}

export function generateRouteFiles(options: RouteFilesOptions) {
  const groupDir = resolve(options.routesDir, "(camox)");
  mkdirSync(resolve(groupDir, "(_preview)"), { recursive: true });
  mkdirSync(resolve(groupDir, "(_studio)"), { recursive: true });
  removeObsoleteRouteFiles(options.routesDir);

  for (const entry of getRouteFileEntries(options)) {
    writeIfChanged(entry.path, entry.content);
  }
}

export function watchRouteFiles(options: RouteFilesOptions & { server: ViteDevServer }) {
  const { server, ...routeFilesOptions } = options;
  const entries = getRouteFileEntries(routeFilesOptions);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox route file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });

  server.watcher.on("unlink", (deletedPath) => {
    const expected = expectedByPath.get(deletedPath);
    if (!expected) return;

    const rel = relative(server.config.root, deletedPath);
    server.config.logger.warn(`Camox route file "${rel}" was deleted — recreating.`, {
      timestamp: true,
    });
    writeFileSync(deletedPath, expected, "utf-8");
  });
}
