import {
  mkdirSync,
  readFileSync,
  readdirSync,
  lstatSync,
  symlinkSync,
  readlinkSync,
  writeFileSync,
} from "node:fs";
import { resolve, relative, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { ViteDevServer } from "vite";
import { writeIfChanged } from "./utils";

const HEADER = `<!-- AUTO-GENERATED BY CAMOX — DO NOT EDIT
This file is managed by the Camox Vite plugin.
Any manual edits will be automatically reverted by the dev server. -->

`;

function generateSkillContent(): string {
  const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
  const skillPath = resolve(sdkRoot, "skills/camox-block/SKILL.md");
  const content = readFileSync(skillPath, "utf-8");
  return HEADER + content;
}

function getSkillFileEntries(appRoot: string) {
  const skillDir = resolve(appRoot, ".agents/skills/camox-block");
  return [
    {
      path: resolve(skillDir, "SKILL.md"),
      content: generateSkillContent(),
    },
  ];
}

export function generateSkillFiles(appRoot: string) {
  const skillDir = resolve(appRoot, ".agents/skills/camox-block");
  mkdirSync(skillDir, { recursive: true });

  for (const entry of getSkillFileEntries(appRoot)) {
    writeIfChanged(entry.path, entry.content);
  }

  ensureClaudeSkillSymlinks(appRoot);
}

/**
 * For each skill directory in `.agents/skills/`, ensure a corresponding
 * symlink exists in `.claude/skills/` pointing to it via a relative path.
 */
function ensureClaudeSkillSymlinks(appRoot: string) {
  const agentsSkillsDir = resolve(appRoot, ".agents/skills");
  const claudeSkillsDir = resolve(appRoot, ".claude/skills");
  mkdirSync(claudeSkillsDir, { recursive: true });

  for (const name of readdirSync(agentsSkillsDir)) {
    const agentSkillPath = join(agentsSkillsDir, name);
    if (!lstatSync(agentSkillPath).isDirectory()) continue;

    const symlinkPath = join(claudeSkillsDir, name);
    const targetRelative = join("../../.agents/skills", name);

    try {
      const existing = readlinkSync(symlinkPath);
      if (existing === targetRelative) continue;
    } catch {
      // symlink doesn't exist or isn't a symlink — create it
    }

    symlinkSync(targetRelative, symlinkPath);
  }
}

export function watchSkillFiles(server: ViteDevServer, appRoot: string) {
  const entries = getSkillFileEntries(appRoot);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox skill file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });
}
