import {
  mkdirSync,
  readFileSync,
  readdirSync,
  lstatSync,
  symlinkSync,
  readlinkSync,
  writeFileSync,
} from "node:fs";
import { resolve, relative, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { ViteDevServer } from "vite";
import { writeIfChanged } from "./utils";

const HEADER = `<!-- AUTO-GENERATED BY CAMOX — DO NOT EDIT
This file is managed by the Camox Vite plugin.
Any manual edits will be automatically reverted by the dev server. -->

`;

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

function getSkillNames(): string[] {
  const skillsDir = resolve(sdkRoot, "skills");
  return readdirSync(skillsDir).filter((name) =>
    lstatSync(resolve(skillsDir, name)).isDirectory(),
  );
}

function generateSkillContent(skillName: string): string {
  const skillPath = resolve(sdkRoot, `skills/${skillName}/SKILL.md`);
  const content = readFileSync(skillPath, "utf-8");
  return HEADER + content;
}

function getSkillFileEntries(appRoot: string) {
  return getSkillNames().map((name) => ({
    path: resolve(appRoot, `.agents/skills/${name}/SKILL.md`),
    content: generateSkillContent(name),
  }));
}

export function generateSkillFiles(appRoot: string) {
  for (const name of getSkillNames()) {
    mkdirSync(resolve(appRoot, `.agents/skills/${name}`), { recursive: true });
  }

  for (const entry of getSkillFileEntries(appRoot)) {
    writeIfChanged(entry.path, entry.content);
  }

  ensureClaudeSkillSymlinks(appRoot);
}

/**
 * For each skill directory in `.agents/skills/`, ensure a corresponding
 * symlink exists in `.claude/skills/` pointing to it via a relative path.
 */
function ensureClaudeSkillSymlinks(appRoot: string) {
  const agentsSkillsDir = resolve(appRoot, ".agents/skills");
  const claudeSkillsDir = resolve(appRoot, ".claude/skills");
  mkdirSync(claudeSkillsDir, { recursive: true });

  for (const name of readdirSync(agentsSkillsDir)) {
    const agentSkillPath = join(agentsSkillsDir, name);
    if (!lstatSync(agentSkillPath).isDirectory()) continue;

    const symlinkPath = join(claudeSkillsDir, name);
    const targetRelative = join("../../.agents/skills", name);

    try {
      const existing = readlinkSync(symlinkPath);
      if (existing === targetRelative) continue;
    } catch {
      // symlink doesn't exist or isn't a symlink — create it
    }

    symlinkSync(targetRelative, symlinkPath);
  }
}

export function watchSkillFiles(server: ViteDevServer, appRoot: string) {
  const entries = getSkillFileEntries(appRoot);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox skill file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });

  server.watcher.on("unlink", (deletedPath) => {
    const expected = expectedByPath.get(deletedPath);
    if (!expected) return;

    const rel = relative(server.config.root, deletedPath);
    server.config.logger.warn(
      `Camox skill file "${rel}" was deleted — recreating.`,
      { timestamp: true },
    );
    writeFileSync(deletedPath, expected, "utf-8");
  });
}
