/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app._dashboard'
import { Route as AppAuthRouteImport } from './routes/_app._auth'
import { Route as AppDashboardIndexRouteImport } from './routes/_app._dashboard/index'
import { Route as AppDashboardProfileRouteImport } from './routes/_app._dashboard/profile'
import { Route as AppDashboardOrgSlugRouteImport } from './routes/_app._dashboard/$orgSlug'
import { Route as AppAuthSignupRouteImport } from './routes/_app._auth/signup'
import { Route as AppAuthResetPasswordRouteImport } from './routes/_app._auth/reset-password'
import { Route as AppAuthLogoutRouteImport } from './routes/_app._auth/logout'
import { Route as AppAuthLoginRouteImport } from './routes/_app._auth/login'
import { Route as AppAuthForgotPasswordRouteImport } from './routes/_app._auth/forgot-password'
import { Route as AppAuthAcceptInvitationRouteImport } from './routes/_app._auth/accept-invitation'
import { Route as AppAuthAuthorizeRouteImport } from './routes/_app._auth/_authorize'
import { Route as AppDashboardOrgSlugIndexRouteImport } from './routes/_app._dashboard/$orgSlug.index'
import { Route as AppDashboardOrgSlugTeamRouteImport } from './routes/_app._dashboard/$orgSlug.team'
import { Route as AppDashboardOrgSlugSettingsRouteImport } from './routes/_app._dashboard/$orgSlug.settings'
import { Route as AppDashboardOrgSlugProjectSlugRouteImport } from './routes/_app._dashboard/$orgSlug.$projectSlug'
import { Route as AppAuthAuthorizeStudioAuthorizeRouteImport } from './routes/_app._auth/_authorize.studio-authorize'
import { Route as AppAuthAuthorizeDevAuthorizeRouteImport } from './routes/_app._auth/_authorize.dev-authorize'
import { Route as AppAuthAuthorizeCliAuthorizedRouteImport } from './routes/_app._auth/_authorize.cli-authorized'
import { Route as AppAuthAuthorizeCliAuthorizeRouteImport } from './routes/_app._auth/_authorize.cli-authorize'
import { Route as AppDashboardOrgSlugProjectSlugIndexRouteImport } from './routes/_app._dashboard/$orgSlug.$projectSlug.index'
import { Route as AppDashboardOrgSlugProjectSlugUsageRouteImport } from './routes/_app._dashboard/$orgSlug.$projectSlug.usage'
import { Route as AppDashboardOrgSlugProjectSlugOverviewRouteImport } from './routes/_app._dashboard/$orgSlug.$projectSlug.overview'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardProfileRoute = AppDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardOrgSlugRoute = AppDashboardOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAuthSignupRoute = AppAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResetPasswordRoute = AppAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthLogoutRoute = AppAuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthForgotPasswordRoute = AppAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAcceptInvitationRoute = AppAuthAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAuthorizeRoute = AppAuthAuthorizeRouteImport.update({
  id: '/_authorize',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppDashboardOrgSlugIndexRoute =
  AppDashboardOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardOrgSlugRoute,
  } as any)
const AppDashboardOrgSlugTeamRoute = AppDashboardOrgSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppDashboardOrgSlugRoute,
} as any)
const AppDashboardOrgSlugSettingsRoute =
  AppDashboardOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppDashboardOrgSlugRoute,
  } as any)
const AppDashboardOrgSlugProjectSlugRoute =
  AppDashboardOrgSlugProjectSlugRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => AppDashboardOrgSlugRoute,
  } as any)
const AppAuthAuthorizeStudioAuthorizeRoute =
  AppAuthAuthorizeStudioAuthorizeRouteImport.update({
    id: '/studio-authorize',
    path: '/studio-authorize',
    getParentRoute: () => AppAuthAuthorizeRoute,
  } as any)
const AppAuthAuthorizeDevAuthorizeRoute =
  AppAuthAuthorizeDevAuthorizeRouteImport.update({
    id: '/dev-authorize',
    path: '/dev-authorize',
    getParentRoute: () => AppAuthAuthorizeRoute,
  } as any)
const AppAuthAuthorizeCliAuthorizedRoute =
  AppAuthAuthorizeCliAuthorizedRouteImport.update({
    id: '/cli-authorized',
    path: '/cli-authorized',
    getParentRoute: () => AppAuthAuthorizeRoute,
  } as any)
const AppAuthAuthorizeCliAuthorizeRoute =
  AppAuthAuthorizeCliAuthorizeRouteImport.update({
    id: '/cli-authorize',
    path: '/cli-authorize',
    getParentRoute: () => AppAuthAuthorizeRoute,
  } as any)
const AppDashboardOrgSlugProjectSlugIndexRoute =
  AppDashboardOrgSlugProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardOrgSlugProjectSlugRoute,
  } as any)
const AppDashboardOrgSlugProjectSlugUsageRoute =
  AppDashboardOrgSlugProjectSlugUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AppDashboardOrgSlugProjectSlugRoute,
  } as any)
const AppDashboardOrgSlugProjectSlugOverviewRoute =
  AppDashboardOrgSlugProjectSlugOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppDashboardOrgSlugProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppDashboardIndexRoute
  '/accept-invitation': typeof AppAuthAcceptInvitationRoute
  '/forgot-password': typeof AppAuthForgotPasswordRoute
  '/login': typeof AppAuthLoginRoute
  '/logout': typeof AppAuthLogoutRoute
  '/reset-password': typeof AppAuthResetPasswordRoute
  '/signup': typeof AppAuthSignupRoute
  '/$orgSlug': typeof AppDashboardOrgSlugRouteWithChildren
  '/profile': typeof AppDashboardProfileRoute
  '/cli-authorize': typeof AppAuthAuthorizeCliAuthorizeRoute
  '/cli-authorized': typeof AppAuthAuthorizeCliAuthorizedRoute
  '/dev-authorize': typeof AppAuthAuthorizeDevAuthorizeRoute
  '/studio-authorize': typeof AppAuthAuthorizeStudioAuthorizeRoute
  '/$orgSlug/$projectSlug': typeof AppDashboardOrgSlugProjectSlugRouteWithChildren
  '/$orgSlug/settings': typeof AppDashboardOrgSlugSettingsRoute
  '/$orgSlug/team': typeof AppDashboardOrgSlugTeamRoute
  '/$orgSlug/': typeof AppDashboardOrgSlugIndexRoute
  '/$orgSlug/$projectSlug/overview': typeof AppDashboardOrgSlugProjectSlugOverviewRoute
  '/$orgSlug/$projectSlug/usage': typeof AppDashboardOrgSlugProjectSlugUsageRoute
  '/$orgSlug/$projectSlug/': typeof AppDashboardOrgSlugProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppDashboardIndexRoute
  '/accept-invitation': typeof AppAuthAcceptInvitationRoute
  '/forgot-password': typeof AppAuthForgotPasswordRoute
  '/login': typeof AppAuthLoginRoute
  '/logout': typeof AppAuthLogoutRoute
  '/reset-password': typeof AppAuthResetPasswordRoute
  '/signup': typeof AppAuthSignupRoute
  '/profile': typeof AppDashboardProfileRoute
  '/cli-authorize': typeof AppAuthAuthorizeCliAuthorizeRoute
  '/cli-authorized': typeof AppAuthAuthorizeCliAuthorizedRoute
  '/dev-authorize': typeof AppAuthAuthorizeDevAuthorizeRoute
  '/studio-authorize': typeof AppAuthAuthorizeStudioAuthorizeRoute
  '/$orgSlug/settings': typeof AppDashboardOrgSlugSettingsRoute
  '/$orgSlug/team': typeof AppDashboardOrgSlugTeamRoute
  '/$orgSlug': typeof AppDashboardOrgSlugIndexRoute
  '/$orgSlug/$projectSlug/overview': typeof AppDashboardOrgSlugProjectSlugOverviewRoute
  '/$orgSlug/$projectSlug/usage': typeof AppDashboardOrgSlugProjectSlugUsageRoute
  '/$orgSlug/$projectSlug': typeof AppDashboardOrgSlugProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/_dashboard': typeof AppDashboardRouteWithChildren
  '/_app/_auth/_authorize': typeof AppAuthAuthorizeRouteWithChildren
  '/_app/_auth/accept-invitation': typeof AppAuthAcceptInvitationRoute
  '/_app/_auth/forgot-password': typeof AppAuthForgotPasswordRoute
  '/_app/_auth/login': typeof AppAuthLoginRoute
  '/_app/_auth/logout': typeof AppAuthLogoutRoute
  '/_app/_auth/reset-password': typeof AppAuthResetPasswordRoute
  '/_app/_auth/signup': typeof AppAuthSignupRoute
  '/_app/_dashboard/$orgSlug': typeof AppDashboardOrgSlugRouteWithChildren
  '/_app/_dashboard/profile': typeof AppDashboardProfileRoute
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/_auth/_authorize/cli-authorize': typeof AppAuthAuthorizeCliAuthorizeRoute
  '/_app/_auth/_authorize/cli-authorized': typeof AppAuthAuthorizeCliAuthorizedRoute
  '/_app/_auth/_authorize/dev-authorize': typeof AppAuthAuthorizeDevAuthorizeRoute
  '/_app/_auth/_authorize/studio-authorize': typeof AppAuthAuthorizeStudioAuthorizeRoute
  '/_app/_dashboard/$orgSlug/$projectSlug': typeof AppDashboardOrgSlugProjectSlugRouteWithChildren
  '/_app/_dashboard/$orgSlug/settings': typeof AppDashboardOrgSlugSettingsRoute
  '/_app/_dashboard/$orgSlug/team': typeof AppDashboardOrgSlugTeamRoute
  '/_app/_dashboard/$orgSlug/': typeof AppDashboardOrgSlugIndexRoute
  '/_app/_dashboard/$orgSlug/$projectSlug/overview': typeof AppDashboardOrgSlugProjectSlugOverviewRoute
  '/_app/_dashboard/$orgSlug/$projectSlug/usage': typeof AppDashboardOrgSlugProjectSlugUsageRoute
  '/_app/_dashboard/$orgSlug/$projectSlug/': typeof AppDashboardOrgSlugProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup'
    | '/$orgSlug'
    | '/profile'
    | '/cli-authorize'
    | '/cli-authorized'
    | '/dev-authorize'
    | '/studio-authorize'
    | '/$orgSlug/$projectSlug'
    | '/$orgSlug/settings'
    | '/$orgSlug/team'
    | '/$orgSlug/'
    | '/$orgSlug/$projectSlug/overview'
    | '/$orgSlug/$projectSlug/usage'
    | '/$orgSlug/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup'
    | '/profile'
    | '/cli-authorize'
    | '/cli-authorized'
    | '/dev-authorize'
    | '/studio-authorize'
    | '/$orgSlug/settings'
    | '/$orgSlug/team'
    | '/$orgSlug'
    | '/$orgSlug/$projectSlug/overview'
    | '/$orgSlug/$projectSlug/usage'
    | '/$orgSlug/$projectSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_auth'
    | '/_app/_dashboard'
    | '/_app/_auth/_authorize'
    | '/_app/_auth/accept-invitation'
    | '/_app/_auth/forgot-password'
    | '/_app/_auth/login'
    | '/_app/_auth/logout'
    | '/_app/_auth/reset-password'
    | '/_app/_auth/signup'
    | '/_app/_dashboard/$orgSlug'
    | '/_app/_dashboard/profile'
    | '/_app/_dashboard/'
    | '/_app/_auth/_authorize/cli-authorize'
    | '/_app/_auth/_authorize/cli-authorized'
    | '/_app/_auth/_authorize/dev-authorize'
    | '/_app/_auth/_authorize/studio-authorize'
    | '/_app/_dashboard/$orgSlug/$projectSlug'
    | '/_app/_dashboard/$orgSlug/settings'
    | '/_app/_dashboard/$orgSlug/team'
    | '/_app/_dashboard/$orgSlug/'
    | '/_app/_dashboard/$orgSlug/$projectSlug/overview'
    | '/_app/_dashboard/$orgSlug/$projectSlug/usage'
    | '/_app/_dashboard/$orgSlug/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_dashboard': {
      id: '/_app/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/profile': {
      id: '/_app/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppDashboardProfileRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/$orgSlug': {
      id: '/_app/_dashboard/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AppDashboardOrgSlugRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_auth/signup': {
      id: '/_app/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppAuthSignupRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/reset-password': {
      id: '/_app/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppAuthResetPasswordRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/logout': {
      id: '/_app/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppAuthLogoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/login': {
      id: '/_app/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/forgot-password': {
      id: '/_app/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppAuthForgotPasswordRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/accept-invitation': {
      id: '/_app/_auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AppAuthAcceptInvitationRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/_authorize': {
      id: '/_app/_auth/_authorize'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthAuthorizeRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_dashboard/$orgSlug/': {
      id: '/_app/_dashboard/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AppDashboardOrgSlugIndexRouteImport
      parentRoute: typeof AppDashboardOrgSlugRoute
    }
    '/_app/_dashboard/$orgSlug/team': {
      id: '/_app/_dashboard/$orgSlug/team'
      path: '/team'
      fullPath: '/$orgSlug/team'
      preLoaderRoute: typeof AppDashboardOrgSlugTeamRouteImport
      parentRoute: typeof AppDashboardOrgSlugRoute
    }
    '/_app/_dashboard/$orgSlug/settings': {
      id: '/_app/_dashboard/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AppDashboardOrgSlugSettingsRouteImport
      parentRoute: typeof AppDashboardOrgSlugRoute
    }
    '/_app/_dashboard/$orgSlug/$projectSlug': {
      id: '/_app/_dashboard/$orgSlug/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$orgSlug/$projectSlug'
      preLoaderRoute: typeof AppDashboardOrgSlugProjectSlugRouteImport
      parentRoute: typeof AppDashboardOrgSlugRoute
    }
    '/_app/_auth/_authorize/studio-authorize': {
      id: '/_app/_auth/_authorize/studio-authorize'
      path: '/studio-authorize'
      fullPath: '/studio-authorize'
      preLoaderRoute: typeof AppAuthAuthorizeStudioAuthorizeRouteImport
      parentRoute: typeof AppAuthAuthorizeRoute
    }
    '/_app/_auth/_authorize/dev-authorize': {
      id: '/_app/_auth/_authorize/dev-authorize'
      path: '/dev-authorize'
      fullPath: '/dev-authorize'
      preLoaderRoute: typeof AppAuthAuthorizeDevAuthorizeRouteImport
      parentRoute: typeof AppAuthAuthorizeRoute
    }
    '/_app/_auth/_authorize/cli-authorized': {
      id: '/_app/_auth/_authorize/cli-authorized'
      path: '/cli-authorized'
      fullPath: '/cli-authorized'
      preLoaderRoute: typeof AppAuthAuthorizeCliAuthorizedRouteImport
      parentRoute: typeof AppAuthAuthorizeRoute
    }
    '/_app/_auth/_authorize/cli-authorize': {
      id: '/_app/_auth/_authorize/cli-authorize'
      path: '/cli-authorize'
      fullPath: '/cli-authorize'
      preLoaderRoute: typeof AppAuthAuthorizeCliAuthorizeRouteImport
      parentRoute: typeof AppAuthAuthorizeRoute
    }
    '/_app/_dashboard/$orgSlug/$projectSlug/': {
      id: '/_app/_dashboard/$orgSlug/$projectSlug/'
      path: '/'
      fullPath: '/$orgSlug/$projectSlug/'
      preLoaderRoute: typeof AppDashboardOrgSlugProjectSlugIndexRouteImport
      parentRoute: typeof AppDashboardOrgSlugProjectSlugRoute
    }
    '/_app/_dashboard/$orgSlug/$projectSlug/usage': {
      id: '/_app/_dashboard/$orgSlug/$projectSlug/usage'
      path: '/usage'
      fullPath: '/$orgSlug/$projectSlug/usage'
      preLoaderRoute: typeof AppDashboardOrgSlugProjectSlugUsageRouteImport
      parentRoute: typeof AppDashboardOrgSlugProjectSlugRoute
    }
    '/_app/_dashboard/$orgSlug/$projectSlug/overview': {
      id: '/_app/_dashboard/$orgSlug/$projectSlug/overview'
      path: '/overview'
      fullPath: '/$orgSlug/$projectSlug/overview'
      preLoaderRoute: typeof AppDashboardOrgSlugProjectSlugOverviewRouteImport
      parentRoute: typeof AppDashboardOrgSlugProjectSlugRoute
    }
  }
}

interface AppAuthAuthorizeRouteChildren {
  AppAuthAuthorizeCliAuthorizeRoute: typeof AppAuthAuthorizeCliAuthorizeRoute
  AppAuthAuthorizeCliAuthorizedRoute: typeof AppAuthAuthorizeCliAuthorizedRoute
  AppAuthAuthorizeDevAuthorizeRoute: typeof AppAuthAuthorizeDevAuthorizeRoute
  AppAuthAuthorizeStudioAuthorizeRoute: typeof AppAuthAuthorizeStudioAuthorizeRoute
}

const AppAuthAuthorizeRouteChildren: AppAuthAuthorizeRouteChildren = {
  AppAuthAuthorizeCliAuthorizeRoute: AppAuthAuthorizeCliAuthorizeRoute,
  AppAuthAuthorizeCliAuthorizedRoute: AppAuthAuthorizeCliAuthorizedRoute,
  AppAuthAuthorizeDevAuthorizeRoute: AppAuthAuthorizeDevAuthorizeRoute,
  AppAuthAuthorizeStudioAuthorizeRoute: AppAuthAuthorizeStudioAuthorizeRoute,
}

const AppAuthAuthorizeRouteWithChildren =
  AppAuthAuthorizeRoute._addFileChildren(AppAuthAuthorizeRouteChildren)

interface AppAuthRouteChildren {
  AppAuthAuthorizeRoute: typeof AppAuthAuthorizeRouteWithChildren
  AppAuthAcceptInvitationRoute: typeof AppAuthAcceptInvitationRoute
  AppAuthForgotPasswordRoute: typeof AppAuthForgotPasswordRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppAuthLogoutRoute: typeof AppAuthLogoutRoute
  AppAuthResetPasswordRoute: typeof AppAuthResetPasswordRoute
  AppAuthSignupRoute: typeof AppAuthSignupRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthAuthorizeRoute: AppAuthAuthorizeRouteWithChildren,
  AppAuthAcceptInvitationRoute: AppAuthAcceptInvitationRoute,
  AppAuthForgotPasswordRoute: AppAuthForgotPasswordRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppAuthLogoutRoute: AppAuthLogoutRoute,
  AppAuthResetPasswordRoute: AppAuthResetPasswordRoute,
  AppAuthSignupRoute: AppAuthSignupRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppDashboardOrgSlugProjectSlugRouteChildren {
  AppDashboardOrgSlugProjectSlugOverviewRoute: typeof AppDashboardOrgSlugProjectSlugOverviewRoute
  AppDashboardOrgSlugProjectSlugUsageRoute: typeof AppDashboardOrgSlugProjectSlugUsageRoute
  AppDashboardOrgSlugProjectSlugIndexRoute: typeof AppDashboardOrgSlugProjectSlugIndexRoute
}

const AppDashboardOrgSlugProjectSlugRouteChildren: AppDashboardOrgSlugProjectSlugRouteChildren =
  {
    AppDashboardOrgSlugProjectSlugOverviewRoute:
      AppDashboardOrgSlugProjectSlugOverviewRoute,
    AppDashboardOrgSlugProjectSlugUsageRoute:
      AppDashboardOrgSlugProjectSlugUsageRoute,
    AppDashboardOrgSlugProjectSlugIndexRoute:
      AppDashboardOrgSlugProjectSlugIndexRoute,
  }

const AppDashboardOrgSlugProjectSlugRouteWithChildren =
  AppDashboardOrgSlugProjectSlugRoute._addFileChildren(
    AppDashboardOrgSlugProjectSlugRouteChildren,
  )

interface AppDashboardOrgSlugRouteChildren {
  AppDashboardOrgSlugProjectSlugRoute: typeof AppDashboardOrgSlugProjectSlugRouteWithChildren
  AppDashboardOrgSlugSettingsRoute: typeof AppDashboardOrgSlugSettingsRoute
  AppDashboardOrgSlugTeamRoute: typeof AppDashboardOrgSlugTeamRoute
  AppDashboardOrgSlugIndexRoute: typeof AppDashboardOrgSlugIndexRoute
}

const AppDashboardOrgSlugRouteChildren: AppDashboardOrgSlugRouteChildren = {
  AppDashboardOrgSlugProjectSlugRoute:
    AppDashboardOrgSlugProjectSlugRouteWithChildren,
  AppDashboardOrgSlugSettingsRoute: AppDashboardOrgSlugSettingsRoute,
  AppDashboardOrgSlugTeamRoute: AppDashboardOrgSlugTeamRoute,
  AppDashboardOrgSlugIndexRoute: AppDashboardOrgSlugIndexRoute,
}

const AppDashboardOrgSlugRouteWithChildren =
  AppDashboardOrgSlugRoute._addFileChildren(AppDashboardOrgSlugRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardOrgSlugRoute: typeof AppDashboardOrgSlugRouteWithChildren
  AppDashboardProfileRoute: typeof AppDashboardProfileRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardOrgSlugRoute: AppDashboardOrgSlugRouteWithChildren,
  AppDashboardProfileRoute: AppDashboardProfileRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
